### ISSUE TITLE
failed building jar

### ISSUE THREAD

**Issue by Machine-3R** [jalmasi/vrspace#1]
Thx for sharing this project. I recently started with babylonjs to (try to) create a (multiplayer) js game on my Quest. Still have a lot to learn.

After installing Maven (I'm not a java developer) I followed the Quickstart (in a cygwin terminal), but the jar file was not created. Also the 2e try in a CMD terminal failed (same messages, except for the downloads) Please help.

Added terminal output (CMD):

[vrspace-failed-building-jar.txt](https://github.com/jalmasi/vrspace/files/5747601/vrspace-failed-building-jar.txt)

**Comment by jalmasi** [comment]
Hi,
the build failed due to one failing test, EventRecorderTest. That is not that important, i.e. it's a component that records all events of a client and plays them back.
You should be able build the server anyway by skipping tests, just run
mvn clean install -DskipTests
I couldn't reproduce that failure though. So I'd appreciate some more info:
- how did you get the source, did you git clone or download the zip?
- mvn --version (I'm most interested in java version in that output but please copy entire output)

**Comment by jalmasi** [comment]
Increased timeouts in EventRecorderTest. Still a bad tests but should not cause false alarm that breaks the build.
