### ISSUE TITLE
visibility of other avatars voice/ui ai bot discord?

### ISSUE THREAD

**Issue by scatterp2** [jalmasi/vrspace#26]
Hi i have a few questions
1) is there any discord or irc chat place for development i mean non forum option?
2) instead of loading my world to template i am loading it directly as the initial logo-room when i go in to for example "cave" the camera is attached to the avatar I would like to know how to adjust this to a view behind the avatar. in the logo room there seems to be a different attachment i would like to be able to attach to the avatar after selection?
3) when going to cave i dont see other avatars unless i go back to an older commit https://github.com/jalmasi/vrspace/tree/094d81c8b736a8c2ca47901f6e3a5b2fce257a6c 
4) i remember when i was using the system previously there was a voice server and you could speak but i can't find that any more?
5) where would i hook the chat to pipe it to irc so the system works over irc ?
6) i found a bot i was chatting with it is it gpt based?

**Comment by jalmasi** [comment]
Hi,
1. No. But you can look me up on social networks, there are contact links at the bottom of vrspace.org home page, we can schedule a live chat.
2. Ah 3rd person view like in games, right? It's doable alright, I have it done on a commercial project. But I have contractual obligations because of that, and I'm not allowed to help you, sorry :( That expires in 3 months or so and I'll implement and publish it then. In the meantime, you can look up babylon.js forums, it's rather common knowledge.
3. Dang, works for me. Any errors in javascript console?
4. OpenVidu alright, short setup instructions here: https://redmine.vrspace.org/projects/vrspace-org/wiki#Docker-and-OpenVidu
5. That would be a nice contribution to the project. Javascript can't connect to irc server due to browser limitations, so vrspace server needs to connect. A world (chatroom) would pub/sub to an irc channel, essentially in the same way openvidu server component does. Client enters a world, subscribes to a channel, leaves world also leaves the channel. Tricky part may be when server creates channel on demand, not sure how that works with irc.
6. Nah, that's an open source bot, BotLibre. There's also connector in the server to a proprietary gpt-based chatbot. Both extend Bot class: https://github.com/jalmasi/vrspace/blob/master/server/src/main/java/org/vrspace/server/obj/Bot.java and implement two methods - selfTest and getResponse. They make some remote api calls.

**Comment by scatterp2** [comment]
Thanks for the concise response 1) ill reach out by email, 2) ah makes sense ok cool 3) ill check and report back 4) perfect 5) irc is actually a pretty simple old protocol "Rooms" are created on the fly with barely any resources all thats needed is for example a couple of log files so what's said in world goes to 1.log what's said in irc will be in 2.log then having irc read and action all that is simply a tail pipe 6) oh i was just curious because i am working with the petals team we just built bloomz which is getting close to chatgpt level of skill
