### ISSUE TITLE
https

### ISSUE THREAD

**Issue by crow34** [jalmasi/vrspace#4]
i am trying to run vrspace from my raspberry pi 4 this is really silly but could you help with setting up a https on raspberry pi 4 so i can access the device data on my quest

**Comment by jalmasi** [comment]
Interesting! :)
You probably don't need "for real" setup of apache proxy server for development, so VRSpace.org server comes with bundled self-signed cert.
Assuming you can build and run vrspace on RPI like we do on PC (never tried it myself), all that you need to do is
java -Dserver.port=8443 -Dserver.ssl.enabled=true -jar target/server-0.4.3-SNAPSHOT.jar
I use 8443 because I have apache listening on 443, 443 should work for you.
Note that order matters, -D stuff has to come before -jar. This way you can override any server properties defined in
https://github.com/jalmasi/vrspace/blob/master/server/src/main/resources/application.properties
Let me know how it works for you, I can even dust off my RPI :)

**Comment by crow34** [comment]
i am currentlly using a rpi 4 with 4gb setup headless and i can report it runs smoothly thankyou

**Comment by saismm9810** [comment]
bro i deoloyed it on default settings and it run on port 8080, but i want to redirect it to my domain. Please tell me how can i do it.
